service: with-iopiperc
provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  timeout: 30
  environment:
    IOPIPE_TOKEN: ${env:IOPIPE_TOKEN}
functions:
  index:
    handler: index.handler
